### ISSUE TITLE
Scanning isn't turning on

### ISSUE THREAD

**Issue by MuradGazibekov** [rani-i/Mi365Locker#1]
For some reasons, scanning isn't turning on. Toast suggest enabling Bluetooth, I did it, but nothing changed. I'm using Xiaomi Mi A1 with Android 9, Kernel version 3.18.120...
![photo_2019-02-13_09-39-05](https://user-images.githubusercontent.com/6669247/52719242-3943cd00-2f73-11e9-9193-3bdf277712c2.jpg)

**Comment by rani-i** [comment]
Also, try enabling location services? BLE using location services.

**Comment by MuradGazibekov** [comment]
> Also, try enabling location services? BLE using location services.

You are right! Thanks! Now everything works.

**Comment by swordapi** [comment]
Enable Bluetooth and GPS then it works xd
