### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by MrMarble** [rani-i/Mi365Locker#2]
What do you mean by adding the scooter to the white list?
Where is the white list?
Do you mean pairing the scooter with my phone first and then use the app?

I use a different phone for testing

**Comment by mishase** [comment]
Hello, MrMarble
Can you give me a compiled apk please ?

**Comment by rani-i** [comment]
if(!device_name.contains("zMiScooter") && !device_name.contains("7513"))
{
   return;
 }

**Comment by rani-i** [comment]
Under OnScanResult in MainActivity.java

**Comment by RotemAkerman** [comment]
why the `!` in `if(!device_name.contains("zMiScooter")`?
shouldn't it be `if(device_name.contains("zMiScooter")`?

**Comment by MrMarble** [comment]
> Under OnScanResult in MainActivity.java

Yeah!
I got it with the first comment, thank you

**Comment by MrMarble** [comment]
> why the `!` in `if(!device_name.contains("zMiScooter")`?
> shouldn't it be `if(device_name.contains("zMiScooter")`?

The thing is that you want the code to work only with your scooter, so that's why if it is not your scooter (the ! in the if) we end the process, it is intended to work only for testing and learning purposes

**Comment by tibzejoker** [comment]
i added an edittext on my fork to whitelist directly from the app via mac adress if it can help :)
