### ISSUE TITLE
changed grandle.propertis java mem. limit to 536m and now is fine with start build, but crash in next:

### ISSUE THREAD

**Issue by y0d4a** [rani-i/Mi365Locker#7]
changed grandle.propertis java mem. limit to 536m and now is fine with start build, but crash in next:
Minimum supported Gradle version is 4.10.1. Current version is 4.4. If using the gradle wrapper, try editing the distributionUrl in C:\Users\y0d4\Downloads\Mi365Locker-master\Mi365Locker-master\gradle\wrapper\gradle-wrapper.properties to gradle-4.10.1-all.zip

_Originally posted by @y0d4a in https://github.com/rani-i/Mi365Locker/issues/6#issuecomment-493749660_

**Comment by y0d4a** [comment]
and changed grandle to right version and got ..

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.

**Comment by criminali** [comment]
HI,how i am install the progrem on my cellphon?
i want unlock the m365 scooter
